# Ejercicio 1> Agregar las variables de entorno necesarias para que la aplicacion "Flask" se conecte a MYSQL
# Ejercicio 2> Agregar php my admin a este docker-compose, y agregar nuevos varietales en la tabla wines del esquema drinks
# Ejercicio 3> Persistir el contenido de la base de datos mysql en disco
# Ejercicio 4> Hostear dos contenedores con la aplicación flask en puertos diferentes en el host (no hay que cambiar la aplicación)
# Ejercicio 5> Agregar al Dockerfile en ./app  la aplicación de linux "nano"

version: "2"

services:
  app:
    build: ./app
    environment: 
      NAME_HELLO: Luis en la primera aplicacion
    depends_on: 
      - db
    ports:
      - 8830:5000 #8830 - localhost del host, 5000 del container


  app2:
    build: ./app
    environment: 
      NAME_HELLO: Luis en la segunda aplicacion
    depends_on: 
      - db
    ports:
      - 8829:5000 

  phpMyAdm:
    image: phpmyadmin/phpmyadmin:5.0.2
    environment: 
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    depends_on: 
      - db
    ports:
      - 8831:80
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: username
      MYSQL_PASSWORD: password
    volumes:
      - ./../db:/var/lib/mysql
      - ./db:/docker-entrypoint-initdb.d/:ro


